Repository Tenshi25/RenkontreAndroid, pull requests merged in 2019-12, with the labels that each got.

#11 Gps distance
  app/src/main/java/master/ccm/renkontreandroid/MapActivity.java
  app/src/main/java/master/ccm/renkontreandroid/utils/GpsUtils.java
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#12 Gps notification distance
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/master/ccm/renkontreandroid/Manager/UserDBManager.java
  app/src/main/java/master/ccm/renkontreandroid/MapActivity.java
  app/src/main/java/master/ccm/renkontreandroid/services/NotificationPhoneService.java
  app/src/main/java/master/ccm/renkontreandroid/services/RefreshMapUiService.java
  app/src/main/java/master/ccm/renkontreandroid/services/interfaces/PositionTrackingService.java
  app/src/main/res/drawable-anydpi/ic_notification_icon.xml
  app/src/main/res/drawable-hdpi/ic_notification_icon.png
  app/src/main/res/drawable-mdpi/ic_notification_icon.png
  app/src/main/res/drawable-xhdpi/ic_notification_icon.png
  app/src/main/res/drawable-xxhdpi/ic_notification_icon.png
Labels: enhancement

#13 add get last known gps data if you does not have gps data
  app/src/main/java/master/ccm/renkontreandroid/Accueil_activity.java
  app/src/main/java/master/ccm/renkontreandroid/utils/GpsUtils.java
Labels: enhancement

#14 Ask localization active when launch app
  app/src/main/java/master/ccm/renkontreandroid/Connexion_activity.java
  app/src/main/java/master/ccm/renkontreandroid/utils/GpsUtils.java
Labels: enhancement

#15 fix ajout soi-même et retour map
  app/src/main/java/master/ccm/renkontreandroid/Accueil_activity.java
  app/src/main/java/master/ccm/renkontreandroid/Form_add_friends_enemy_activity.java
Labels: bug

#16 commentaire remi
  app/src/main/java/master/ccm/renkontreandroid/Accueil_activity.java
  app/src/main/java/master/ccm/renkontreandroid/Connexion_activity.java
  app/src/main/java/master/ccm/renkontreandroid/Form_add_friends_enemy_activity.java
  app/src/main/java/master/ccm/renkontreandroid/Inscription_activity.java
  app/src/main/java/master/ccm/renkontreandroid/Manager/UserDBManager.java
Labels: documentation

#18 Comment kevin
  app/src/main/java/master/ccm/renkontreandroid/ContactPhoneActivity.java
  app/src/main/java/master/ccm/renkontreandroid/Inscription_activity.java
  app/src/main/java/master/ccm/renkontreandroid/ListFriendsEnemy_activity.java
  app/src/main/java/master/ccm/renkontreandroid/MapActivity.java
  app/src/main/java/master/ccm/renkontreandroid/Profile_activity.java
  app/src/main/java/master/ccm/renkontreandroid/services/GpsService.java
  app/src/main/java/master/ccm/renkontreandroid/services/GpsUpdateReceiver.java
  app/src/main/java/master/ccm/renkontreandroid/services/NotificationPhoneService.java
  app/src/main/java/master/ccm/renkontreandroid/services/RefreshMapUiService.java
  app/src/main/java/master/ccm/renkontreandroid/utils/GpsUtils.java
Labels: documentation

#19 interface utilisateur maj
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/friends_enemy_item_list.xml
  app/src/main/res/layout/layout_list_friends_enemy.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: enhancement

#20 manage permissions in a class
  app/src/main/java/master/ccm/renkontreandroid/Connexion_activity.java
  app/src/main/java/master/ccm/renkontreandroid/MapActivity.java
  app/src/main/java/master/ccm/renkontreandroid/utils/PermissionUtils.java
Labels: enhancement

#21 Modify readme
  README.md
Labels: documentation

#24 change zoom level
  app/src/main/java/master/ccm/renkontreandroid/MapActivity.java
Labels: enhancement

#26 Ask permission for map
  app/src/main/java/master/ccm/renkontreandroid/Accueil_activity.java
  app/src/main/java/master/ccm/renkontreandroid/utils/PermissionUtils.java
Labels: bug
